name: Protect Main Branch

on:
  push:
    branches:
      - main

jobs:
  no-push:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if trying to push to main
        run: |
          echo "Pushing directly to the main branch is not allowed."
          exit 1
